### ISSUE TITLE
rancid check improvements

### ISSUE THREAD

**Issue by FlorianHeigl** [chrpinedo/nagios-like-monitoring#2]
Hi,

currently there are some issues I would like to work on, what do you think:

### remove the "is the device up for backup" monitoring

- it does not go to CRIT if the actual backup connection fails (just got this case)
- if the host is down, we'll have that in Check_MK anyway

### add function to check if there is a backup

- currently the check checks if there is a log file for the group, but it could be full of errors
- i would check that there is a backup file larger than 0 bytes and less old than 2 days
- since the rancid logs are more like of the ```printout from a mainframe, hand to operator for review``` type, I don't think there is hope in parsing the logs.

Do you have advice for parsing the logs?
Are you interested in the changes?

**Comment by chrpinedo** [comment]
Hi @FlorianHeigl,

thanks for your comments! However, I don't work any longer with check_mk, rancid... so it is difficult for me to improve current scripts. If you are interested in improving the files, I can consider the way you prefer to proceed:
- you can fork my repo and I can set my repo as archive-read-only or even delete. I could also point your repo as the more recent version...
- I could give you access to this repo to commit against this repo
- ...

What you prefer. 

Regards,

**Comment by FlorianHeigl** [comment]
Btw: Thanks for your reply!

I'm still waiting for some accounts on switches I need to run backups for, after that I'll work on the check again. I'd prefer the version where I commit to your repo since I don't have much to say about the other checks. It'll be good enough so other people can have the updates.

**Comment by chrpinedo** [comment]
So, I sent you an invitation to collaborate in this repo. Check if you can collaborate just now :)

**Comment by FlorianHeigl** [comment]
i have the contributor tag, i tried to directly push a branch that didn't work. i'll check out more carefully tonight, what/how i gotta do. ;-)

**Comment by chrpinedo** [comment]
It seems that you need to approve my contribution request...
![imagen](https://user-images.githubusercontent.com/2324630/82898905-59c24b80-9f5a-11ea-8d5f-685a0cec50d5.png)

**Comment by FlorianHeigl** [comment]
access OK, i'll open individual issues as i change stuff and prep the prs

TY!
